### PR TITLE
Fix cryptic error caused by using all defaults

### LINKED ISSUE #79: Default value for B_SLOPE results in error
In the main function `bbwp()` the default value for 'B_SLOPE' == NULL.
This results in an error when no values are given for 'B_SLOPE' and 'B_SLOPE_DEGREE' caused by assertion on 'B_SLOPE' which must be of type 'logical' not 'NULL'.

### PR DESCRIPTION
**Pull request by BrentWHR**
Resolves #79

### CODE REVIEW

File: tests/testthat/test-bbwp.R [hunk 1]
```diff
@@ -426,4 +426,38 @@ test <- bbwp(B_SOILTYPE_AGR = c('dekzand', 'loess', 'rivierklei'),
       tolerance = 0.01)
   })
   
-  
\ No newline at end of file
+  test_that('B_SLOPE and B_SLOPE_DEGREE can both be used but at leatst one needst to be given',
```
Comment (SvenVw) [inline tests/testthat/test-bbwp.R:429]: Typo

File: R/bbwp_main.R [hunk 2]
```diff
@@ -40,7 +40,7 @@
 #' @param output (string) a vector specifying the output type of the function. Options: scores, measures 
 #' 
 #' @details
```
Comment (SvenVw) [inline R/bbwp_main.R:42]: Add to parameters that B_SLOPE is deprecated

**Review by SvenVw — CHANGES_REQUESTED** [review]

**Review by SvenVw — APPROVED** [review]
👍
